from rest_framework import serializers
from .models import Item

class ItemSerializer(serializers.ModelSerializer):
    # Make QR code read-only if generated by the server
    qr_code = serializers.ImageField(read_only=True)

    class Meta:
        model = Item
        fields = '__all__'
